### ISSUE TITLE
Crest getSettingData()

### ISSUE THREAD

**Issue by csandovalgt** [bitrix-tools/crest#1]
Hi, I'm using CRest. I have created my application in Bitrix but I'm getting the message: 

Array ( [error] => no_install_app [error_information] => error install app, pls install local application )

Looking the crest.php file I see that it is trying to get information from the file settings.json:
 file_exists(__DIR__ . '/settings.json')
but I don't see this file in the project.

Do you know where I can get this file?

**Comment by VladsBitrix** [comment]
Hello!
If you use local application: need write on create app set "install url" to install.php
if you use webhook: need only set C_REST_WEB_HOOK_URL in settings.php

And open checkserver.php mb need set permission for a folder etc
