### ISSUE TITLE
Custom Field With Multiple Selection Doesn't Work

### ISSUE THREAD

**Issue by forionne-admin** [bitrix-tools/crest#10]
Hi,

I have a custom field with multiple selection. 

![image](https://user-images.githubusercontent.com/111186750/188494137-6c572367-bbdb-4a00-9106-47dc1aa95d63.png)

`'UF_CRM_1618612593' => "246"`

or 

`'UF_CRM_1618612593' => 246`

or 

```
'UF_CRM_1618612593' => [
          ['VALUE' => 246]
        ]
```

doesn't work. How can I add contact via API to a field with multiple selection?

**Comment by muravikov** [comment]
https://training.bitrix24.com/rest_help/crm/deals/crm_deal_userfield_add.php
the easiest thing is to fill in your field through the entity card, and then read the transaction data through the REST API.
Multiple selection it will probably look like this 'UF_CRM_1618612593' => [246,248,256]

**Comment by forionne-admin** [comment]
[246,248,256] was the only thing I haven't tried, silly me :)

I can confirm that I can post to fields with multiple options like that..

Thank you..
